name: Node.js CI/CD Pipeline

on:
  push:
    branches:
    - feature/add-ci

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: 'Build Docker Image'
      run: |
        docker build -t twizoff/devops-assignment:latest .

    - name: 'Push Docker Image'
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u twizoff --password-stdin
        docker push twizoff/devops-assignment:latest

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: 'SSH into the server and deploy'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.PUBLIC_SSH_KEY }} #a
        script: |
          # Ensure the target deployment directory exists
          sudo mkdir -p /opt/docker

          # Copy Docker Compose file to the server
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/docker/

          # SSH into the server and deploy using docker-compose
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /opt/docker/ && docker-compose up -d"
