name: Node.js CI/CD Pipeline

on:
  push:
    branches:
    - feature/add-ci

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: 'Build Docker Image'
      run: |
        docker build -t twizoff/devops-assignment:latest .

    - name: 'Push Docker Image'
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u twizoff --password-stdin
        docker push twizoff/devops-assignment:latest

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: 'SSH into the server and deploy'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          whoami

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.PUBLIC_SSH_KEY }}
        script: "whoami          \n# Ensure the target deployment directory exists\nsudo mkdir -p /opt/docker\n#magic___^_^___line\n# Copy Docker Compose file to the server\nscp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/docker/\n#magic___^_^___line\n# SSH into the server and deploy using docker-compose\nssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} \"cd /opt/docker/ && docker-compose up -d\"\n"
